# Generated by Django 4.1a1 on 2022-05-22 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("travels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="travel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="travel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="place",
                to="travels.travel",
            ),
        ),
        migrations.AddField(
            model_name="lodging",
            name="travel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lodging",
                to="travels.travel",
            ),
        ),
    ]
