# Generated by Django 4.1a1 on 2022-05-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travel",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="travel",
            name="longitude",
        ),
    ]
